.\" Manpage for Raspberry Pi Smart System.
.\" Contact jake@jr0.org to correct errors or typos.
.TH man 8 "28 Apr 2020" "1.0" "rpi-smart-system man page"
.SH NAME
rpi smart system \- a simple gpio relay interface for raspberry pi 
.SH SYNOPSIS
rpi-smart-system [OPTION]... [NAME]... [VALUE]...
.SH DESCRIPTION
A simple gpio relay interface for raspberry pi
.SH OPTIONS
-v	Show relay setup verbosely (Needs to be last item)
e.g. rpi-smart-system -t light -v
.br
-t	Toggle a relay using name
.br
-s	Set a relay to value using name
.br
-l	List all relays and their status 
.SH BUG
if flags are not passed to rushnote, rushnote errors out and closes
.SH AUTHOR
Jake Roggenbuck, jake@jr0.org
